/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MiHijoRouteImport } from './routes/mi-hijo'
import { Route as KioskoRouteImport } from './routes/kiosko'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReportesRouteImport } from './routes/_app.reportes'
import { Route as AppMatriculaRouteImport } from './routes/_app.matricula'
import { Route as AppHorarioRouteImport } from './routes/_app.horario'
import { Route as AppFamiliasRouteImport } from './routes/_app.familias'
import { Route as AppFacturacionRouteImport } from './routes/_app.facturacion'
import { Route as AppEquipoRouteImport } from './routes/_app.equipo'
import { Route as AppEjecucionRouteImport } from './routes/_app.ejecucion'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBibliotecaRouteImport } from './routes/_app.biblioteca'
import { Route as AppAsistenciaRouteImport } from './routes/_app.asistencia'
import { Route as AppNinosIndexRouteImport } from './routes/_app.ninos.index'
import { Route as AppNinosIdRouteImport } from './routes/_app.ninos.$id'
import { Route as AppFacturacionCierreRouteImport } from './routes/_app.facturacion.cierre'
import { Route as AppFacturacionCartasRouteImport } from './routes/_app.facturacion.cartas'
import { Route as AppFacturacionLoteIdRouteImport } from './routes/_app.facturacion.$loteId'
import { Route as AppClinicoGraficasRouteImport } from './routes/_app.clinico.graficas'
import { Route as AppAsistenciaCarnetsRouteImport } from './routes/_app.asistencia.carnets'

const MiHijoRoute = MiHijoRouteImport.update({
  id: '/mi-hijo',
  path: '/mi-hijo',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskoRoute = KioskoRouteImport.update({
  id: '/kiosko',
  path: '/kiosko',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportesRoute = AppReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AppRoute,
} as any)
const AppMatriculaRoute = AppMatriculaRouteImport.update({
  id: '/matricula',
  path: '/matricula',
  getParentRoute: () => AppRoute,
} as any)
const AppHorarioRoute = AppHorarioRouteImport.update({
  id: '/horario',
  path: '/horario',
  getParentRoute: () => AppRoute,
} as any)
const AppFamiliasRoute = AppFamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturacionRoute = AppFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipoRoute = AppEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AppRoute,
} as any)
const AppEjecucionRoute = AppEjecucionRouteImport.update({
  id: '/ejecucion',
  path: '/ejecucion',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppAsistenciaRoute = AppAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => AppRoute,
} as any)
const AppNinosIndexRoute = AppNinosIndexRouteImport.update({
  id: '/ninos/',
  path: '/ninos/',
  getParentRoute: () => AppRoute,
} as any)
const AppNinosIdRoute = AppNinosIdRouteImport.update({
  id: '/ninos/$id',
  path: '/ninos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturacionCierreRoute = AppFacturacionCierreRouteImport.update({
  id: '/cierre',
  path: '/cierre',
  getParentRoute: () => AppFacturacionRoute,
} as any)
const AppFacturacionCartasRoute = AppFacturacionCartasRouteImport.update({
  id: '/cartas',
  path: '/cartas',
  getParentRoute: () => AppFacturacionRoute,
} as any)
const AppFacturacionLoteIdRoute = AppFacturacionLoteIdRouteImport.update({
  id: '/$loteId',
  path: '/$loteId',
  getParentRoute: () => AppFacturacionRoute,
} as any)
const AppClinicoGraficasRoute = AppClinicoGraficasRouteImport.update({
  id: '/clinico/graficas',
  path: '/clinico/graficas',
  getParentRoute: () => AppRoute,
} as any)
const AppAsistenciaCarnetsRoute = AppAsistenciaCarnetsRouteImport.update({
  id: '/carnets',
  path: '/carnets',
  getParentRoute: () => AppAsistenciaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kiosko': typeof KioskoRoute
  '/mi-hijo': typeof MiHijoRoute
  '/asistencia': typeof AppAsistenciaRouteWithChildren
  '/biblioteca': typeof AppBibliotecaRoute
  '/dashboard': typeof AppDashboardRoute
  '/ejecucion': typeof AppEjecucionRoute
  '/equipo': typeof AppEquipoRoute
  '/facturacion': typeof AppFacturacionRouteWithChildren
  '/familias': typeof AppFamiliasRoute
  '/horario': typeof AppHorarioRoute
  '/matricula': typeof AppMatriculaRoute
  '/reportes': typeof AppReportesRoute
  '/asistencia/carnets': typeof AppAsistenciaCarnetsRoute
  '/clinico/graficas': typeof AppClinicoGraficasRoute
  '/facturacion/$loteId': typeof AppFacturacionLoteIdRoute
  '/facturacion/cartas': typeof AppFacturacionCartasRoute
  '/facturacion/cierre': typeof AppFacturacionCierreRoute
  '/ninos/$id': typeof AppNinosIdRoute
  '/ninos/': typeof AppNinosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kiosko': typeof KioskoRoute
  '/mi-hijo': typeof MiHijoRoute
  '/asistencia': typeof AppAsistenciaRouteWithChildren
  '/biblioteca': typeof AppBibliotecaRoute
  '/dashboard': typeof AppDashboardRoute
  '/ejecucion': typeof AppEjecucionRoute
  '/equipo': typeof AppEquipoRoute
  '/facturacion': typeof AppFacturacionRouteWithChildren
  '/familias': typeof AppFamiliasRoute
  '/horario': typeof AppHorarioRoute
  '/matricula': typeof AppMatriculaRoute
  '/reportes': typeof AppReportesRoute
  '/asistencia/carnets': typeof AppAsistenciaCarnetsRoute
  '/clinico/graficas': typeof AppClinicoGraficasRoute
  '/facturacion/$loteId': typeof AppFacturacionLoteIdRoute
  '/facturacion/cartas': typeof AppFacturacionCartasRoute
  '/facturacion/cierre': typeof AppFacturacionCierreRoute
  '/ninos/$id': typeof AppNinosIdRoute
  '/ninos': typeof AppNinosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/kiosko': typeof KioskoRoute
  '/mi-hijo': typeof MiHijoRoute
  '/_app/asistencia': typeof AppAsistenciaRouteWithChildren
  '/_app/biblioteca': typeof AppBibliotecaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/ejecucion': typeof AppEjecucionRoute
  '/_app/equipo': typeof AppEquipoRoute
  '/_app/facturacion': typeof AppFacturacionRouteWithChildren
  '/_app/familias': typeof AppFamiliasRoute
  '/_app/horario': typeof AppHorarioRoute
  '/_app/matricula': typeof AppMatriculaRoute
  '/_app/reportes': typeof AppReportesRoute
  '/_app/asistencia/carnets': typeof AppAsistenciaCarnetsRoute
  '/_app/clinico/graficas': typeof AppClinicoGraficasRoute
  '/_app/facturacion/$loteId': typeof AppFacturacionLoteIdRoute
  '/_app/facturacion/cartas': typeof AppFacturacionCartasRoute
  '/_app/facturacion/cierre': typeof AppFacturacionCierreRoute
  '/_app/ninos/$id': typeof AppNinosIdRoute
  '/_app/ninos/': typeof AppNinosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kiosko'
    | '/mi-hijo'
    | '/asistencia'
    | '/biblioteca'
    | '/dashboard'
    | '/ejecucion'
    | '/equipo'
    | '/facturacion'
    | '/familias'
    | '/horario'
    | '/matricula'
    | '/reportes'
    | '/asistencia/carnets'
    | '/clinico/graficas'
    | '/facturacion/$loteId'
    | '/facturacion/cartas'
    | '/facturacion/cierre'
    | '/ninos/$id'
    | '/ninos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kiosko'
    | '/mi-hijo'
    | '/asistencia'
    | '/biblioteca'
    | '/dashboard'
    | '/ejecucion'
    | '/equipo'
    | '/facturacion'
    | '/familias'
    | '/horario'
    | '/matricula'
    | '/reportes'
    | '/asistencia/carnets'
    | '/clinico/graficas'
    | '/facturacion/$loteId'
    | '/facturacion/cartas'
    | '/facturacion/cierre'
    | '/ninos/$id'
    | '/ninos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/kiosko'
    | '/mi-hijo'
    | '/_app/asistencia'
    | '/_app/biblioteca'
    | '/_app/dashboard'
    | '/_app/ejecucion'
    | '/_app/equipo'
    | '/_app/facturacion'
    | '/_app/familias'
    | '/_app/horario'
    | '/_app/matricula'
    | '/_app/reportes'
    | '/_app/asistencia/carnets'
    | '/_app/clinico/graficas'
    | '/_app/facturacion/$loteId'
    | '/_app/facturacion/cartas'
    | '/_app/facturacion/cierre'
    | '/_app/ninos/$id'
    | '/_app/ninos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  KioskoRoute: typeof KioskoRoute
  MiHijoRoute: typeof MiHijoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mi-hijo': {
      id: '/mi-hijo'
      path: '/mi-hijo'
      fullPath: '/mi-hijo'
      preLoaderRoute: typeof MiHijoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosko': {
      id: '/kiosko'
      path: '/kiosko'
      fullPath: '/kiosko'
      preLoaderRoute: typeof KioskoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reportes': {
      id: '/_app/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AppReportesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matricula': {
      id: '/_app/matricula'
      path: '/matricula'
      fullPath: '/matricula'
      preLoaderRoute: typeof AppMatriculaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/horario': {
      id: '/_app/horario'
      path: '/horario'
      fullPath: '/horario'
      preLoaderRoute: typeof AppHorarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/familias': {
      id: '/_app/familias'
      path: '/familias'
      fullPath: '/familias'
      preLoaderRoute: typeof AppFamiliasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facturacion': {
      id: '/_app/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof AppFacturacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipo': {
      id: '/_app/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AppEquipoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ejecucion': {
      id: '/_app/ejecucion'
      path: '/ejecucion'
      fullPath: '/ejecucion'
      preLoaderRoute: typeof AppEjecucionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca': {
      id: '/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asistencia': {
      id: '/_app/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AppAsistenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ninos/': {
      id: '/_app/ninos/'
      path: '/ninos'
      fullPath: '/ninos/'
      preLoaderRoute: typeof AppNinosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ninos/$id': {
      id: '/_app/ninos/$id'
      path: '/ninos/$id'
      fullPath: '/ninos/$id'
      preLoaderRoute: typeof AppNinosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facturacion/cierre': {
      id: '/_app/facturacion/cierre'
      path: '/cierre'
      fullPath: '/facturacion/cierre'
      preLoaderRoute: typeof AppFacturacionCierreRouteImport
      parentRoute: typeof AppFacturacionRoute
    }
    '/_app/facturacion/cartas': {
      id: '/_app/facturacion/cartas'
      path: '/cartas'
      fullPath: '/facturacion/cartas'
      preLoaderRoute: typeof AppFacturacionCartasRouteImport
      parentRoute: typeof AppFacturacionRoute
    }
    '/_app/facturacion/$loteId': {
      id: '/_app/facturacion/$loteId'
      path: '/$loteId'
      fullPath: '/facturacion/$loteId'
      preLoaderRoute: typeof AppFacturacionLoteIdRouteImport
      parentRoute: typeof AppFacturacionRoute
    }
    '/_app/clinico/graficas': {
      id: '/_app/clinico/graficas'
      path: '/clinico/graficas'
      fullPath: '/clinico/graficas'
      preLoaderRoute: typeof AppClinicoGraficasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asistencia/carnets': {
      id: '/_app/asistencia/carnets'
      path: '/carnets'
      fullPath: '/asistencia/carnets'
      preLoaderRoute: typeof AppAsistenciaCarnetsRouteImport
      parentRoute: typeof AppAsistenciaRoute
    }
  }
}

interface AppAsistenciaRouteChildren {
  AppAsistenciaCarnetsRoute: typeof AppAsistenciaCarnetsRoute
}

const AppAsistenciaRouteChildren: AppAsistenciaRouteChildren = {
  AppAsistenciaCarnetsRoute: AppAsistenciaCarnetsRoute,
}

const AppAsistenciaRouteWithChildren = AppAsistenciaRoute._addFileChildren(
  AppAsistenciaRouteChildren,
)

interface AppFacturacionRouteChildren {
  AppFacturacionLoteIdRoute: typeof AppFacturacionLoteIdRoute
  AppFacturacionCartasRoute: typeof AppFacturacionCartasRoute
  AppFacturacionCierreRoute: typeof AppFacturacionCierreRoute
}

const AppFacturacionRouteChildren: AppFacturacionRouteChildren = {
  AppFacturacionLoteIdRoute: AppFacturacionLoteIdRoute,
  AppFacturacionCartasRoute: AppFacturacionCartasRoute,
  AppFacturacionCierreRoute: AppFacturacionCierreRoute,
}

const AppFacturacionRouteWithChildren = AppFacturacionRoute._addFileChildren(
  AppFacturacionRouteChildren,
)

interface AppRouteChildren {
  AppAsistenciaRoute: typeof AppAsistenciaRouteWithChildren
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEjecucionRoute: typeof AppEjecucionRoute
  AppEquipoRoute: typeof AppEquipoRoute
  AppFacturacionRoute: typeof AppFacturacionRouteWithChildren
  AppFamiliasRoute: typeof AppFamiliasRoute
  AppHorarioRoute: typeof AppHorarioRoute
  AppMatriculaRoute: typeof AppMatriculaRoute
  AppReportesRoute: typeof AppReportesRoute
  AppClinicoGraficasRoute: typeof AppClinicoGraficasRoute
  AppNinosIdRoute: typeof AppNinosIdRoute
  AppNinosIndexRoute: typeof AppNinosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAsistenciaRoute: AppAsistenciaRouteWithChildren,
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEjecucionRoute: AppEjecucionRoute,
  AppEquipoRoute: AppEquipoRoute,
  AppFacturacionRoute: AppFacturacionRouteWithChildren,
  AppFamiliasRoute: AppFamiliasRoute,
  AppHorarioRoute: AppHorarioRoute,
  AppMatriculaRoute: AppMatriculaRoute,
  AppReportesRoute: AppReportesRoute,
  AppClinicoGraficasRoute: AppClinicoGraficasRoute,
  AppNinosIdRoute: AppNinosIdRoute,
  AppNinosIndexRoute: AppNinosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  KioskoRoute: KioskoRoute,
  MiHijoRoute: MiHijoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
